name: Build Android APK

on:
  push:
    branches: [ "main", "master", "ana" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Indir
      uses: actions/checkout@v4

    - name: Java Kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Flutter Kur
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Projeyi Bul ve APK Yap
      run: |
        PROJECT_DIR=$(dirname $(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1))
        echo "Bulunan klasor: $PROJECT_DIR"
        cd $PROJECT_DIR
        flutter pub get
        flutter build apk --release

    - name: APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: uygulama-apk
        path: "**/build/app/outputs/flutter-apk/app-release.apk"
